version: "3.4"

services:
    api:
        build:
          context: ./app
          dockerfile: Dockerfile
        ports:
          - "8080:80"
        depends_on:
          - db

    db:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        ports:
          - "1433:1433"

        environment:
            SA_PASSWORD: "Bangtans2001"
            ACCEPT_EULA: "Y"

    client:
      build:
        context: ./client
        dockerfile: Dockerfile
      image: gstart
      ports:
      - "5000:5000"